XSConsoleLangFriendlyNames.py

Since the `ext` driver now defaults to EXT4, update the displayed type
for this kind of SR. Displaying 'Ext4' would be wrong in situations
where the SR was created before the default changed, so we simply remove
the digit and make it just 'Ext'.
Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>

Display 'Ext' instead of 'Ext3' for `ext` SRs

---

XSConsoleData.py

Signed-off-by: BenjiReis <benjamin.reis@vates.fr>

Use XAPI to edit DNS entries within xsconsole

---

plugins-base/XSFeatureStatus.py

Differentiate when master is unreachable, XAPI service is down, no network configured and
also do not display an error when XAPI is finishing starting up
Signed-off-by: BenjiReis <benjamin.reis@vates.fr>

Display clearer error message when XAPI unreachable

---

XSConsoleData.py

The textual product version is the "marketing" version so this is what
should be shown in most places in xsconsole.
Show the numeric product version (which doesn't really have a purpose)
only in the detailed software information page.
The versions in xsconsole look like this:
* coreversion - 8 Cloud - shown on the front page
* fullversion - 8 Cloud (8.3.0-cloud) - shown on the detailed software
information page
* shortversion - 8 Cloud - shown in other places
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>

CP-40640: Show the textual rather than numeric product version

---

XSConsoleData.py

Since the Dom0 move to Centos7 the keymaps i386 directory was moved to the `/lib/kbd/keymaps/legacy` directory
This change fixes the xsconsole warnings of missing keymaps (as it was looking in the wrong place)
```
[root@lcy2-dt73 ~]# ls /lib/kbd/keymaps/
legacy  xkb
[root@lcy2-dt73 ~]# ls /lib/kbd/keymaps/legacy/
amiga  atari  i386  include  mac  ppc  sun
```

Keymaps moved to /lib/kbd/keymaps/legacy/i386

---

MaintenanceReadme.txt
XSConsole.py
XSConsoleBases.py
XSConsoleCurses.py
XSConsoleData.py
XSConsoleDataUtils.py
XSConsoleFields.py
XSConsoleHotData.py
XSConsoleImporter.py
XSConsoleMenus.py
XSConsoleMetrics.py
XSConsoleState.py
XSConsoleTask.py
XSConsoleTerm.py
XSConsoleUtils.py
plugins-base/XSFeatureDRBackup.py
plugins-base/XSFeatureDRRestore.py
plugins-base/XSFeatureSRCreate.py
plugins-base/XSFeatureSaveBugReport.py
plugins-base/XSFeatureSystem.py
plugins-base/XSFeatureUploadBugReport.py
plugins-oem/XSFeatureOEMBackup.py
plugins-oem/XSFeatureOEMRestore.py
plugins-oem/XSFeatureUpdate.py
simpleconfig.py

Split part2 out of https://github.com/xapi-project/xsconsole/pull/15
This is literally just converting 'commands' to 'subprocess', updating 'print' syntax, converting 'iteritems' to 'items', removing the use of 'types' and some misc changes.

Pr15 split part2

---

XSConsoleCurses.py
XSConsoleData.py
XSConsoleDataUtils.py
XSConsoleDialoguePane.py
XSConsoleFields.py
XSConsoleImporter.py
XSConsoleLayout.py
XSConsoleMenus.py
XSConsoleUtils.py
plugins-base/XSFeatureEULA.py
plugins-base/XSFeatureSRCommon.py
plugins-base/XSFeatureSRInfo.py
plugins-base/XSFeatureVMCommon.py
plugins-base/XSFeatureVMInfo.py
simpleconfig.py

This is removing the use 'file' and updating 'xmlrpc, socketserver, urllib' syntax for python3. For this part, we didn't consider python2 compatibility considering it will make code complicated.

Pr15 split part3

---

XSConsoleHotData.py

Fix this regression which was introduced by #17, commit 5: "Misc changes":
https://github.com/xapi-project/xsconsole/pull/17/commits/29b179366062f20587de3812e80c0a7567298122#diff-7a99a3d0d9dc721b20052fba067d76350ea7734d0f26607afec287ad0a296f7c
In https://github.com/xapi-project/xsconsole/pull/18#issuecomment-1791844449, Andrew said that breaking the Python2 master branch before the Python3 branch works is not and option, therefore fix this first.
With Python3, after all commits from #20 are also applied, XSConsole still says:
Therfore, the situation is clear: Fix Python2 first.

Fix PR#17 commit 'misc changes', it broke listing and editing Storage Repositories

---

XSConsoleHotData.py

According to the agreement with Andrew at https://github.com/xapi-project/xsconsole/pull/18#issuecomment-1791844449, Python2-compatible changes can go to the master branch freely, before branching of the Python3-only changes into a py3 branch:
> So, please can we collect together all commits which are py2-safe fixes, which can get reviewed and merged freely, and please keep all commits which break compatibility with py2 in a separate single PR so it can be merged all in one go. The final commit on the py3 branch should bump the major version number of xsconsole seeing as its a bit step change.
Qin Zhang （张琴）authored this commit and I reviewed it:
- The `__hash__` function (needed in addition to __eq__ for Python3's datamodel) is already in the code, so this change is fine for Py2 and Py3

Remove the use of __cmp__ and use __eq__ instead

---

plugins-base/XSFeatureLocalShell.py

There's no reason to keep 3 shell processes to execute one. Remove "()" in command to avoid one additional process. Add "exec" on last command to replace current process. Remove exports, not necessary as changing one single command environment.
This changes this:
```sh
$ pstree -alp | grep -4 bash
...
|-python,2051 /usr/lib64/xsconsole/XSConsole.py -f root
|   `-sh,3238 -c ( export HOME=/root; export TMOUT=300 && cat /etc/motd && /bin/bash --login )
|       `-sh,3239 -c ( export HOME=/root; export TMOUT=300 && cat /etc/motd && /bin/bash --login )
|           `-bash,3241 --login
...
```
to this:
```sh
$ pstree -alp | grep -4 bash
...
|-python,2044 /usr/lib64/xsconsole/XSConsole.py -f root
|   `-bash,3128 --login
...
```

Avoid useless processes launching shell

---

XSConsoleMetrics.py

When doing MRG test for xsconsole with Python3 enabled, we found Host Performance Information didn't have any valid data. This is beacause URLopener doesn't work in Python3.
Fix this for python3 compatibility.
Manually tested with both python2 and python3
- with python 2 
Installed rt-next and replaced the XSConsoleMetrics.py file. 
Job id (3918187)
- with python 3: 
Installed the build: https://koji.eng.citrite.net/kojifiles/repos/pbb-stephenche-xs8/159194/x86_64/
Job id(3918352)

CA-388179: Host Performance Information was unavailable with Python3

---

plugins-base/XSFeatureNTP.py

Courtesy of the tool `darker` (applies black to the changes in a `git diff`),
here is a set of a few minor formatting suggestions it makes for #35 for the file XSFeatureNTP.py:
This is an incremental PR for #35 (it can be merged/squashed into #35 or reviewed afterwards):
This PR only applies to the 2nd commit of #35, so it could be pulled and squashed into it:
[CA-369899: Add NTP options DHCP|Default|Manual|None](https://github.com/xapi-project/xsconsole/pull/35/commits/a992e30e1b1c533c4cf6b7320c42402b69f346c0#top)
I ran:
```py
pip install darker
darker -r master -S -l 88 .
```
(88 columns is the default of black - take look yourself, it looks sensible to me too)
As this branch is on the same origin repo, you can e.g. run
```py
git fetch origin
git cherry-pick …
```

XSFeatureNTP: Apply selected suggestions courtesy of darker(from black)

---

XSConsoleData.py

Courtesy of the tool `darker` (applies black to the changes in a `git diff`),
here is a set of a few minor formatting suggestions it makes for #35.
This is an incremental PR for #35 (it can be merged/squashed into #35 or reviewed afterwards):
This PR only applies to the 2nd commit of #35, so it could be pulled and squashed into it:
[CA-369899: Add NTP options DHCP|Default|Manual|None](https://github.com/xapi-project/xsconsole/pull/35/commits/a992e30e1b1c533c4cf6b7320c42402b69f346c0#top)
I ran:
```py
pip install darker
darker -r master -S -l 88 .
```
(88 columns is the default of black - take look yourself, it looks sensible to me too)
As this branch is on the same origin repo, you can e.g. run
```py
git fetch origin
git cherry-pick aef00d4d7d73b58ef05a2a62e4fe5a9eb5adcfde
git rebase -i …
```

Apply selected suggestions courtesy of darker (from black)

---

Makefile
XSConsoleAuth.py
XSConsoleConstants.py
XSConsoleData.py
XSConsoleDialoguePane.py
XSConsoleFields.py
XSConsoleStandard.py
XSConsoleTerm.py
XSConsoleUtils.py
plugins-base/XSFeatureInterface.py
plugins-base/XSFeatureNTP.py
plugins-base/XSMenuLayout.py

These changes implement NTP control in xsconsole to match the NTP options available in the host-installer
To keep the xsconsole time up to date, the console must use monotonic time (via ncurses) to ensure the console doesn't wait for any negative timesteps before updating (there is an open PR for this behaviour in XenServer) (the console will also update the time upon receiving user input if monotonic time is not used)
Also remove the testing option for the NTP feature as ntpstat is no longer present.
DHCP - Use DHCP server as NTP server
Default - Use the default centos pool NTP servers
Manual - Use manually specified NTP servers
None - Set time manually, no NTP

CA-369899: Add NTP options DHCP|Default|Manual|None

---

plugins-base/XSFeatureNTP.py

plugins-base/XSFeatureNTP.py: Add docstrings to new and changed functions
Using the gained understanding from code review of #35, add docstrings to functions that are added or significantly changed in #35.

CA369899: Add docstrings to added/changed functions in XSFeatureNTP.py

---

XSConsoleDialogueBases.py
XSConsoleTask.py
plugins-base/XSFeatureSRCreate.py

The XSConsoleAuth set socket timout value to 15 seconds,
and it's not enough for the SR.create.
Use xenapi.Async call instead.
Test passed:

CA-388527 xsconsole: 'timed out' when creating an ISCSI SR

---

plugins-base/XSFeatureSRCreate.py

In the previous PR, in the `__init__`of `ProgressDialogue`, I put the keywork arguments after the positional arguments. But I forgot to do the same in `CommitCreate` when we construct a `ProgressDialogue`
Test the OnComplete callback was called:
```
Jun  7 01:07:47 xrtmia-11-05 xsconsole: stephen TaskEntry.Status: %s
Jun  7 01:07:47 xrtmia-11-05 xsconsole: True
Jun  7 01:07:47 xrtmia-11-05 xsconsole: SR.create complete and call back is called
Jun  7 01:07:47 xrtmia-11-05 xsconsole: {'opaqueRef': 'OpaqueRef:752a9389-edae-1b43-d96a-1fa24166d44a', 'type': 'any', 'hash': 6275920129978874783}
```

CA-388527: Fix keyword argument order error

---

XSConsoleDialogueBases.py

The PR https://github.com/xapi-project/xsconsole/pull/42 uses keyword-only argument which is not supported in Python2 (led to build errors, although the Python file worked on XS8) . In XS8, we still uses python2, so fix this to work both in python2 and python3
Build success in XS8:
```
INFO: Done(/tmp/kojienv.crBpR8EVY/scratch/xsconsole-11.0.5-1.1.g52be83b.xs8.src.rpm) Config(pb-stephenche-x8) 0 minutes 5 seconds
INFO: Results and/or logs in: /home/stephenche/xs9/xsconsole.spec/SRPM//build
Finish: run
```
Build success in XS9:
```
INFO: Done(/tmp/kojienv.ZZrHfUNdW/scratch/xsconsole-11.0.5-1.1.g52be83b.xs9.src.rpm) Config(pb-stephenche-x9) 0 minutes 4 seconds
INFO: Results and/or logs in: /home/stephenche/xs9/xsconsole.spec/SRPM//build
Finish: run
```

CA-388527: Keep python2 and python3 compatibility

---

XSConsoleData.py

In some cases we may fail to query the host CPUs due to an invalid reference, in this case we should log the failure and not add it into the list of host CPUs.
In the event of a failure we receive a list of the form: `['HANDLE_INVALID', 'host_cpu', '<uuid>']`
In a success we receive a dictionary which is later used to populate the number of CPUs per name but does not check that the contents of host_CPUs is a list of dictionaries.

CA-390512: Improved xenapi error handling

---

plugins-base/XSFeatureDRRestore.py

Modifies functionality to understand the use of legacy format VDIs:
- Adds an option to search for a legacy format VDI if a new one is not found
- Handles the case where multiple legacy VDIs are identified
- Passes the appropriate option to `xe-restore-metadata` when needed
This is XSA-459 / CVE-2024-31144
Also update the subprocess calls to be compatible with python3

Updates to Portable SR functionality

---

XSConsoleAuth.py

Pam passwd service is updated to handle updating password only Here before offer local shell, we want to authenticate username and password, thus password-auth pam service should be used
This fix is compatible with XS8 and XS9

CA-395025: Local command shell login failed on XS9

---

XSConsoleData.py
plugins-base/XSFeatureRemoteShell.py

Currently, xsconsole uses systemd to manage ssh service. In the ssh configuration feature (CP-50702), ssh's status is saved in xapi DB and is updated by xapi API.
So change the way of managing ssh to xapi API in xsconsole to keep the ssh's status updating.

CP-54010: Use xapi for ssh in xsconsole

---

.github/workflows/main.yml
plugins-base/XSFeatureNetworkReset.py

A new proposed change in networkd will replace the interface-rename functionality to order the network devices. The result of the ordering performed by interface-rename is to rename the devices like eth0, eth1, etc. The new change in networkd will not rename the devices any more. Consequently, the use of hard-coded eth<N> in network reset in xsconsole should be eliminated to cope with the new change.
Additionally, the new networkd replacing the interface rename functionality will perform the network reset with xapi together.
The interface rename functionality will be deprecated in the future.

CP-54442: Update for network devices not being renamed

---

.github/workflows/main.yml
XSConsoleData.py
plugins-base/XSFeatureRemoteShell.py

This PR aims to allows users to configure SSH Auto Mode. This functionality enables the system to automatically enable or disable SSH service based on XAPI conditions.

CP-54331 Enable XSConsole to Configure Auto mode

---

plugins-base/XSFeatureInterface.py

The supporter host could just be having trouble connecting to the coordinator.

When no interfaces are found, clarify this does not mean there are no interfaces at all

---

plugins-base/XSFeatureNetworkReset.py

The issue is the "MANAGEMENT_INTERFACE" in /etc/xensource-inventory is not cleared in a networking reset. While the networkd is still trying to read the value of "MANAGEMENT_INTERFACE" as the bridge name. This caused the new network interface was added into the bridge before reset.

CA-415864: MANAGEMENT_INTERFACE is not cleared in network reset

---

XSConsoleData.py

xsconsole can set ntp to `Use DHCP NTP Servers` or `Use Default NTP Servers`, `Provide NTP Servers Manually`. This is so-called `dhcp` `defaul`t and `manual` mode.
When switching from other modes to DHCP, the DHCP-provided NTP servers should be added to the Chrony sources. Conversely, they should be removed when switching away from DHCP.
In XS9, the ntp-dhcp server path is outdated as the chrony version update, comparing to XS8.
xs8-chrony: version 3.2, the server file with dhclient is `/var/lib/dhclient/chrony.servers.$interface`
xs9-chrony: version 4.6.1, the server file with dhclient is `/run/chrony-dhcp/$interface.sources`
It takes effect by write `server $source iburst prefer` to `/run/chrony-dhcp/$interface.sources` and `/run/chrony-dhcp` is sourcedir in `/etc/chrony.conf`.

CA-417641 Update ntp-dhcp server file path
